numero1 = int(input("Digite um Número: "))
numero2 = int(input("Digite um Número: "))
print("Dividendo:")
print(numero1)
print("Divisor:")
print(numero2)
print("Quociente:")
print(numero1/numero2)
print("Resto:")
print(numero1%numero2)
