nome = input("Digite um nome: ")
print("Todo o nome:")
print(nome)
print("Primeiro Caractere:")
print(nome[0])
print("Último Caractere:")
print(nome[-1])
print("Do Primeiro até o Terceiro Caractere:")
print(nome[:3])
print("Quarto Caractere:")
print(nome[3])
print("Os Dois Últimos Caracteres:")
print(nome[-2:])
