import math
print("Figura cujo ângulo é:")
print("Seno:")
print(math.sin(80))
print("Co-seno:")
print(math.cos(80))
print("Tangente:")
print(math.tan(80))
print("Secante:")
print(1/math.cos(80))
print("Co-secante:")
print(1/math.sin(80))
print("Co-tangente:")
print(1/math.tan(80))
      
